const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const S={audio:null,url:null,buffer:null,duration:0,start:0,end:0,image:null,imgURL:null,x:.5,y:.5,zoom:1,format:"16:9",style:"pulse",ctx:null,source:null,analyser:null,playing:false};
const F={"16:9":[1920,1080],"9:16":[1080,1920],"1:1":[1080,1080]};
function go(n){$$(".screen").forEach(x=>x.classList.toggle("active",x.dataset.screen===n));$("#status").textContent=n==="home"?"Listo":n;}
$$("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));
const fmt=s=>{s=Math.max(0,s||0);return `${Math.floor(s/60)}:${Math.floor(s%60).toString().padStart(2,"0")}`};

$("#audioInput").onchange=async e=>{const f=e.target.files[0];if(!f)return;S.audio=f;S.url=URL.createObjectURL(f);$("#audioPlayer").src=S.url;$("#audioPanel").classList.remove("hidden");const A=window.AudioContext||window.webkitAudioContext;S.ctx||=(S.ctx=new A);try{S.buffer=await S.ctx.decodeAudioData(await f.arrayBuffer());S.duration=S.buffer.duration;S.start=0;S.end=S.duration;$("#startRange").max=S.duration;$("#endRange").max=S.duration;$("#endRange").value=S.duration;$("#audioInfo").textContent=`${f.name} · ${fmt(S.duration)}`;$("#startLabel").textContent="0:00";$("#endLabel").textContent=fmt(S.duration);$("#toImage").disabled=false;drawWave()}catch(e){alert("No pude leer ese audio. Prueba MP3 o WAV.")}};
function drawWave(){const c=$("#waveform"),x=c.getContext("2d"),w=c.width=c.clientWidth*2,h=c.height=200;x.clearRect(0,0,w,h);if(!S.buffer)return;const d=S.buffer.getChannelData(0),step=Math.ceil(d.length/w);x.strokeStyle="#b8ff4a";x.beginPath();for(let i=0;i<w;i++){let mi=1,ma=-1;for(let j=i*step;j<Math.min((i+1)*step,d.length);j++){mi=Math.min(mi,d[j]);ma=Math.max(ma,d[j])}x.moveTo(i,h/2+mi*h*.4);x.lineTo(i,h/2+ma*h*.4)}x.stroke()}
function range(which){let v=+which.value;if(which.id==="startRange")S.start=Math.min(v,S.end-.01);else S.end=Math.max(v,S.start+.01);$("#startRange").value=S.start;$("#endRange").value=S.end;$("#startLabel").textContent=fmt(S.start);$("#endLabel").textContent=fmt(S.end);drawWave()}
$("#startRange").oninput=e=>range(e.target);$("#endRange").oninput=e=>range(e.target);

function resizeImage(){const f=F[S.format],frame=$("#frame");frame.style.aspectRatio=`${f[0]}/${f[1]}`;const c=$("#imageCanvas");c.width=frame.clientWidth*2;c.height=frame.clientHeight*2;c.dataset.ratio=S.format;drawImage()}
function drawImage(){const c=$("#imageCanvas"),x=c.getContext("2d"),w=c.width,h=c.height;x.clearRect(0,0,w,h);if(!S.image)return;x.fillStyle="#111";x.fillRect(0,0,w,h);const sc=Math.max(w/S.image.width,h/S.image.height)*S.zoom,dw=S.image.width*sc,dh=S.image.height*sc;x.drawImage(S.image,w*S.x-dw/2,h*S.y-dh/2,dw,dh)}
$("#imageInput").onchange=e=>{const f=e.target.files[0];if(!f)return;S.imgURL=URL.createObjectURL(f);const im=new Image();im.onload=()=>{S.image=im;S.x=S.y=.5;S.zoom=1;$("#zoomRange").disabled=false;$("#centerImage").disabled=false;$("#toViz").disabled=false;$("#imageHint").style.display="none";resizeImage()};im.src=S.imgURL};
$("#zoomRange").oninput=e=>{S.zoom=+e.target.value;drawImage()};$("#centerImage").onclick=()=>{S.x=S.y=.5;S.zoom=1;$("#zoomRange").value=1;drawImage()};
let drag=false,lx,ly;$("#imageCanvas").onpointerdown=e=>{drag=true;$("#imageCanvas").setPointerCapture(e.pointerId);lx=e.clientX;ly=e.clientY};$("#imageCanvas").onpointermove=e=>{if(!drag)return;const r=$("#imageCanvas").getBoundingClientRect();S.x=Math.max(0,Math.min(1,S.x+(e.clientX-lx)/r.width));S.y=Math.max(0,Math.min(1,S.y+(e.clientY-ly)/r.height));lx=e.clientX;ly=e.clientY;drawImage()};$("#imageCanvas").onpointerup=()=>drag=false;

$$(".format").forEach(b=>b.onclick=()=>{$$(".format").forEach(x=>x.classList.remove("active"));b.classList.add("active");S.format=b.dataset.format;resizeImage();drawViz()});
$$(".style").forEach(b=>b.onclick=()=>{$$(".style").forEach(x=>x.classList.remove("active"));b.classList.add("active");S.style=b.dataset.style;drawViz()});

const vc=$("#vizCanvas"),vx=vc.getContext("2d");
function scene(c,w,h,t,data){c.fillStyle="#050506";c.fillRect(0,0,w,h);if(S.image){const sc=Math.max(w/S.image.width,h/S.image.height)*S.zoom,dw=S.image.width*sc,dh=S.image.height*sc;c.globalAlpha=.82;c.drawImage(S.image,w*S.x-dw/2,h*S.y-dh/2,dw,dh);c.globalAlpha=1}const e=data?.reduce((a,b)=>a+b,0)/(data?.length||1)||.2;if(S.style==="pulse"){c.beginPath();c.arc(w/2,h/2,Math.min(w,h)*(.22+e*.04),0,7);c.strokeStyle="#b8ff4a";c.lineWidth=Math.max(3,w/500);c.stroke()}else if(S.style==="wave"){c.strokeStyle="#b8ff4a";c.lineWidth=Math.max(2,w/700);c.beginPath();for(let i=0;i<80;i++){const xx=i*w/79,yy=h*.8+Math.sin(i*.55+t)*e*h*.18;if(i)c.lineTo(xx,yy);else c.moveTo(xx,yy)}c.stroke()}else{for(let i=0;i<36;i++){const a=i*2.4+t*.15,r=Math.min(w,h)*(.2+(i%8)*.035),xx=w/2+Math.cos(a)*r,yy=h/2+Math.sin(a)*r;c.fillStyle=i%2?"#b8ff4a99":"#fff9";c.beginPath();c.arc(xx,yy,3+e*9,0,7);c.fill()}}}
function data(){if(!S.analyser)return null;const a=new Uint8Array(S.analyser.frequencyBinCount);S.analyser.getByteFrequencyData(a);return [...a.slice(0,64)].map(v=>v/255)}
function drawViz(){const f=F[S.format];vc.width=f[0];vc.height=f[1];const box=$("#viz"),sc=Math.min(box.clientWidth/f[0,(window.innerHeight*.6)/f[1]);vc.style.width=`${f[0]*sc}px`;vc.style.height=`${f[1]*sc}px`;scene(vx,f[0],f[1],performance.now()/500,data())}
function play(){if(!S.buffer)return;const A=window.AudioContext||window.webkitAudioContext;S.ctx||=(S.ctx=new A);S.ctx.resume();if(S.source)try{S.source.stop()}catch{}S.source=S.ctx.createBufferSource();S.analyser=S.ctx.createAnalyser();S.source.buffer=S.buffer;S.source.connect(S.analyser);S.analyser.connect(S.ctx.destination);S.source.start(0,S.start,S.end-S.start);S.playing=true;$("#playBtn").textContent="■ Detener";S.source.onended=()=>{S.playing=false;$("#playBtn").textContent="▶ Reproducir"};const loop=()=>{if(!S.playing)return;drawViz();requestAnimationFrame(loop)};loop()}
$("#playBtn").onclick=()=>{if(S.playing){try{S.source.stop()}catch{}S.playing=false;$("#playBtn").textContent="▶ Reproducir"}else play()};

async function exportVideo(){if(!S.buffer||!S.image)return alert("Carga audio e imagen primero.");if(!window.MediaRecorder||!HTMLCanvasElement.prototype.captureStream)return alert("Este navegador no permite exportar video desde Canvas. Prueba Chrome o Edge.");const [w,h]=F[S.format],c=document.createElement("canvas");c.width=w;c.height=h;const cx=c.getContext("2d"),stream=c.captureStream(30),A=window.AudioContext||window.webkitAudioContext,ac=new A(),dest=ac.createMediaStreamDestination(),src=ac.createBufferSource();src.buffer=S.buffer;src.connect(dest);stream.addTrack(dest.stream.getAudioTracks()[0]);const mime=["video/mp4;codecs=avc1.42E01E,mp4a.40.2","video/webm;codecs=vp9,opus","video/webm"].find(m=>MediaRecorder.isTypeSupported(m));if(!mime)return alert("Tu navegador no ofrece un formato de video compatible.");const chunks=[],rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:6000000});rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);const done=new Promise(r=>rec.onstop=r);const dur=S.end-S.start;src.start(0,S.start,dur);rec.start(500);const t0=performance.now();function loop(n){const p=Math.min(1,(n-t0)/1000/dur);scene(cx,w,h,n/500,[p]);$("#progress").classList.remove("hidden");$("#progress").style.width=`${p*100}%`;if(p<1)requestAnimationFrame(loop);else rec.stop()}requestAnimationFrame(loop);await done;src.stop();ac.close();const type=mime.split(";")[0],blob=new Blob(chunks,{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`music-release-kit.${type==="video/mp4"?"mp4":"webm"}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
$("#exportBtn").onclick=exportVideo;
window.addEventListener("resize",()=>{resizeImage();drawViz()});resizeImage();drawViz();
