(() => {
"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const FORMATS={"16:9":{width:1920,height:1080,label:"1920 × 1080"},"9:16":{width:1080,height:1920,label:"1080 × 1920"},"1:1":{width:1080,height:1080,label:"1080 × 1080"}};
const state={format:"16:9",style:"pulse",audioFile:null,audioBuffer:null,audioURL:null,duration:0,start:0,end:0,image:null,imageURL:null,imageX:.5,imageY:.5,zoom:1,audioContext:null,analyser:null,source:null,playing:false,animationFrame:null};
const audioInput=$("#audioInput"),imageInput=$("#imageInput"),startRange=$("#startRange"),endRange=$("#endRange"),startLabel=$("#startLabel"),endLabel=$("#endLabel"),audioInfo=$("#audioInfo"),playAudioButton=$("#playAudio"),centerImageButton=$("#centerImage"),zoomRange=$("#zoomRange"),previewCanvas=$("#previewCanvas"),previewContext=previewCanvas.getContext("2d"),emptyState=$("#emptyState"),exportButton=$("#exportButton"),exportStatus=$("#exportStatus"),progressContainer=$("#progressContainer"),progressBar=$("#progressBar"),browserStatus=$("#browserStatus"),previewStatus=$("#previewStatus"),formatLabel=$("#formatLabel");
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
function formatTime(s){s=Math.max(0,Number(s)||0);return `${Math.floor(s/60)}:${Math.floor(s%60).toString().padStart(2,"0")}`;}
function checkBrowser(){const a=typeof HTMLCanvasElement!=="undefined"&&typeof HTMLCanvasElement.prototype.captureStream==="function",b=typeof MediaRecorder!=="undefined";browserStatus.textContent=a&&b?"Exportación disponible":"Exportación limitada";browserStatus.classList.add(a&&b?"good":"warning");}
function setFormat(f){if(!FORMATS[f])return;state.format=f;$$(".format").forEach(b=>b.classList.toggle("active",b.dataset.format===f));formatLabel.textContent=FORMATS[f].label;resizePreview();draw();}
$$(".format").forEach(b=>b.addEventListener("click",()=>setFormat(b.dataset.format)));
$$(".style").forEach(b=>b.addEventListener("click",()=>{state.style=b.dataset.style;$$(".style").forEach(x=>x.classList.toggle("active",x.dataset.style===state.style));draw();}));
audioInput.addEventListener("change",async e=>{const f=e.target.files[0];if(!f)return;try{await loadAudio(f)}catch(err){console.error(err);alert("No pude cargar este audio. Prueba con otro MP3 o WAV.")}});
async function loadAudio(file){if(state.audioURL)URL.revokeObjectURL(state.audioURL);state.audioFile=file;state.audioURL=URL.createObjectURL(file);const C=window.AudioContext||window.webkitAudioContext;if(!C)throw Error("Web Audio no está disponible.");if(!state.audioContext)state.audioContext=new C();state.audioBuffer=await state.audioContext.decodeAudioData(await file.arrayBuffer());state.duration=state.audioBuffer.duration;state.start=0;state.end=state.duration;startRange.disabled=endRange.disabled=false;playAudioButton.disabled=false;startRange.max=endRange.max=String(state.duration);startRange.value=0;endRange.value=state.duration;startLabel.textContent="0:00";endLabel.textContent=formatTime(state.duration);audioInfo.textContent=`${file.name} · ${formatTime(state.duration)}`;previewStatus.textContent="Audio cargado";updateExportAvailability();draw();}
startRange.addEventListener("input",()=>{state.start=Math.min(Number(startRange.value),state.end-.05);startRange.value=state.start;startLabel.textContent=formatTime(state.start)});
endRange.addEventListener("input",()=>{state.end=Math.max(Number(endRange.value),state.start+.05);endRange.value=state.end;endLabel.textContent=formatTime(state.end)});
playAudioButton.addEventListener("click",async()=>state.playing?stopAudio():await playSelection());
async function playSelection(){const C=window.AudioContext||window.webkitAudioContext;if(!C)return alert("Tu navegador no soporta Web Audio.");if(!state.audioContext)state.audioContext=new C();await state.audioContext.resume();stopAudio();state.source=state.audioContext.createBufferSource();state.analyser=state.audioContext.createAnalyser();state.analyser.fftSize=256;state.source.buffer=state.audioBuffer;state.source.connect(state.analyser);state.analyser.connect(state.audioContext.destination);state.source.onended=()=>{state.playing=false;playAudioButton.textContent="▶ Escuchar selección"};state.source.start(0,state.start,state.end-state.start);state.playing=true;playAudioButton.textContent="■ Detener";animate();}
function stopAudio(){if(state.source){try{state.source.stop()}catch(_){ }state.source=null}state.playing=false;if(state.animationFrame)cancelAnimationFrame(state.animationFrame);state.animationFrame=null;playAudioButton.textContent="▶ Escuchar selección";}
imageInput.addEventListener("change",e=>{const f=e.target.files[0];if(!f)return;if(state.imageURL)URL.revokeObjectURL(state.imageURL);state.imageURL=URL.createObjectURL(f);const im=new Image();im.onload=()=>{state.image=im;state.imageX=.5;state.imageY=.5;state.zoom=1;zoomRange.disabled=false;centerImageButton.disabled=false;zoomRange.value=1;previewStatus.textContent="Audio + portada listos";emptyState.classList.add("hidden");updateExportAvailability();draw()};im.onerror=()=>alert("No pude cargar esa imagen.");im.src=state.imageURL;});
zoomRange.addEventListener("input",()=>{state.zoom=Number(zoomRange.value);draw()});
centerImageButton.addEventListener("click",()=>{state.imageX=.5;state.imageY=.5;state.zoom=1;zoomRange.value=1;draw()});
let dragging=false,lastPointerX=0,lastPointerY=0;
previewCanvas.addEventListener("pointerdown",e=>{if(!state.image)return;dragging=true;previewCanvas.setPointerCapture(e.pointerId);lastPointerX=e.clientX;lastPointerY=e.clientY});
previewCanvas.addEventListener("pointermove",e=>{if(!dragging||!state.image)return;const r=previewCanvas.getBoundingClientRect();state.imageX=clamp(state.imageX+(e.clientX-lastPointerX)/r.width,0,1);state.imageY=clamp(state.imageY+(e.clientY-lastPointerY)/r.height,0,1);lastPointerX=e.clientX;lastPointerY=e.clientY;draw()});
previewCanvas.addEventListener("pointerup",()=>dragging=false);previewCanvas.addEventListener("pointercancel",()=>dragging=false);
function resizePreview(){const f=FORMATS[state.format];previewCanvas.width=f.width;previewCanvas.height=f.height;const p=previewCanvas.parentElement,w=Math.max(200,p.clientWidth-40),h=Math.max(200,window.innerHeight-180),scale=Math.min(w/f.width,h/f.height);previewCanvas.style.width=`${f.width*scale}px`;previewCanvas.style.height=`${f.height*scale}px`;}
function drawImage(c,w,h){if(!state.image)return;const s=Math.max(w/state.image.width,h/state.image.height)*state.zoom,iw=state.image.width*s,ih=state.image.height*s,x=w*state.imageX-iw/2,y=h*state.imageY-ih/2;c.drawImage(state.image,x,y,iw,ih);}
function draw(){const w=previewCanvas.width,h=previewCanvas.height;previewContext.fillStyle="#050505";previewContext.fillRect(0,0,w,h);if(state.image)drawImage(previewContext,w,h);drawVisualizerEffect(previewContext,w,h,getAudioEnergy(),performance.now());}
function drawVisualizerEffect(c,w,h,e,time){const t=time/1000,cx=w/2,cy=h/2;if(state.style==="pulse"){c.beginPath();c.arc(cx,cy,Math.min(w,h)*(.18+e*.12),0,Math.PI*2);c.strokeStyle="#b8ff4a";c.lineWidth=Math.max(4,w/450);c.stroke();}if(state.style==="wave"){c.beginPath();c.strokeStyle="#b8ff4a";c.lineWidth=Math.max(3,w/600);for(let i=0;i<120;i++){const x=i/119*w,y=cy+Math.sin(i*.35+t*3)*e*h*.18;i?c.lineTo(x,y):c.moveTo(x,y)}c.stroke();}if(state.style==="neon"){for(let i=0;i<40;i++){const a=i/40*Math.PI*2+t*.5,r=Math.min(w,h)*(.18+(i%8)*.025+e*.08),x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r;c.beginPath();c.fillStyle=i%2===0?"#b8ff4a":"#fff";c.arc(x,y,3+e*8,0,Math.PI*2);c.fill();}}}
function getAudioEnergy(){if(!state.analyser)return .15;const d=new Uint8Array(state.analyser.frequencyBinCount);state.analyser.getByteFrequencyData(d);let t=0;for(const v of d)t+=v;return t/d.length/255;}
function animate(){if(!state.playing)return;draw();state.animationFrame=requestAnimationFrame(animate);}
exportButton.addEventListener("click",exportVideo);
async function exportVideo(){if(!state.audioBuffer||!state.image)return alert("Primero sube una canción y una portada.");if(typeof HTMLCanvasElement.prototype.captureStream!=="function")return alert("Este navegador no permite capturar el canvas para crear el video. Prueba Chrome en un computador.");if(typeof MediaRecorder==="undefined")return alert("Este navegador no tiene MediaRecorder disponible.");const C=window.AudioContext||window.webkitAudioContext;if(!C)return alert("Web Audio no está disponible.");exportButton.disabled=true;exportStatus.textContent="Preparando video...";progressContainer.classList.remove("hidden");progressBar.style.width="0%";const f=FORMATS[state.format],canvas=document.createElement("canvas");canvas.width=f.width;canvas.height=f.height;const c=canvas.getContext("2d"),stream=canvas.captureStream(30),ac=new C();await ac.resume();const dest=ac.createMediaStreamDestination(),src=ac.createBufferSource();src.buffer=state.audioBuffer;src.connect(dest);dest.stream.getAudioTracks().forEach(t=>stream.addTrack(t));const types=["video/webm;codecs=vp9,opus","video/webm;codecs=vp8,opus","video/webm"],mime=types.find(t=>MediaRecorder.isTypeSupported(t));if(!mime){await ac.close();exportButton.disabled=false;exportStatus.textContent="Este navegador no ofrece un formato compatible.";return;}const chunks=[],rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:6000000});rec.ondataavailable=e=>{if(e.data&&e.data.size)chunks.push(e.data)};const stopped=new Promise(r=>rec.addEventListener("stop",r,{once:true})),dur=Math.max(.1,state.end-state.start),start=performance.now();rec.start();src.start(0,state.start,dur);function render(now){const p=clamp((now-start)/1000/dur,0,1);c.fillStyle="#050505";c.fillRect(0,0,canvas.width,canvas.height);drawImage(c,canvas.width,canvas.height);drawVisualizerEffect(c,canvas.width,canvas.height,.25,now);progressBar.style.width=`${p*100}%`;exportStatus.textContent=`Exportando... ${Math.round(p*100)}%`;p<1?requestAnimationFrame(render):rec.stop()}requestAnimationFrame(render);await stopped;try{src.stop()}catch(_){}stream.getTracks().forEach(t=>t.stop());await ac.close();const blob=new Blob(chunks,{type:"video/webm"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download="music-visualizer.webm";document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);progressBar.style.width="100%";exportStatus.textContent="Video exportado correctamente.";exportButton.disabled=false;}
function updateExportAvailability(){const ready=Boolean(state.audioBuffer&&state.image);exportButton.disabled=!ready;exportStatus.textContent=ready?"Listo para exportar.":state.audioBuffer?"Ahora sube una portada.":"Sube una canción y una portada para comenzar.";}
window.addEventListener("resize",()=>{resizePreview();draw()});
checkBrowser();setFormat("16:9");resizePreview();updateExportAvailability();draw();
})();